# Generated by Django 3.2.5 on 2022-01-01 09:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_super', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.TextField()),
                ('shipper_phone', models.TextField()),
                ('shipper_address', models.TextField()),
                ('shipper_email', models.TextField()),
                ('reciever_name', models.TextField()),
                ('reciever_phone', models.TextField()),
                ('reciever_address', models.TextField()),
                ('reciever_email', models.TextField()),
                ('type_of_shipment', models.TextField()),
                ('weight', models.TextField()),
                ('courier', models.TextField()),
                ('packages', models.TextField()),
                ('mode', models.TextField()),
                ('product', models.TextField()),
                ('quantity', models.TextField()),
                ('payment_mode', models.TextField()),
                ('total_freight', models.TextField()),
                ('carrier', models.TextField()),
                ('carrier_reference_no', models.TextField()),
                ('depature_time', models.TextField()),
                ('origin', models.TextField()),
                ('destination', models.TextField()),
                ('pickup_date', models.TextField()),
                ('pickup_time', models.TextField()),
                ('exected_delivery_date', models.TextField()),
                ('comment', models.TextField()),
                ('uuid', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
