# Generated by Django 3.2.5 on 2022-01-01 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shipment_create_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.TextField()),
                ('status', models.TextField()),
                ('updated_by', models.TextField()),
                ('remarks', models.TextField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shipment')),
            ],
        ),
    ]
