# Generated by Django 3.2.5 on 2022-01-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='location',
            field=models.TextField(default='England'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
