# Generated by Django 3.2.5 on 2022-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220101_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='invoice',
            field=models.TextField(default='lglkgugqqm'),
        ),
    ]
