# Generated by Django 3.2.5 on 2022-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shipment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='consignment_detail',
            field=models.TextField(default='Private Shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='invoice',
            field=models.TextField(default='qlqwjtoenz'),
        ),
    ]
