# Generated by Django 3.2.5 on 2022-01-28 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20220101_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField()),
                ('status', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='users.shipment')),
            ],
        ),
    ]
