# Generated by Django 3.2.5 on 2022-01-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='remarks',
            new_name='remark',
        ),
    ]
